server:
  port: 80

spring:
  application:
    name: cloud_consumer_order80
  cloud:
    # spring cloud consul for discovery
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true # 优先使用服务ip进行注册


