server:
  port: 9527

spring:
  # 配置微服务的名字
  application:
    name: cloud-gateway

  # 将网管服务配置到注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true # 优先通过IP来查找服务
    gateway:
      # 配置网关路由
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service            #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - VIP=diamond # 自定义的断言规则
            - name: VIP
              args:
                userType: goal
            # - Query=gender, man
            # - RemoteAddr=10.3.12.51/24
            # - Method=GET, POST
            # - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达
            # - Host=**.aimin.com # 测试携带的参数为指定请求的目标主机和端口
            # - Cookie=username,am
#            - Path=/XYZ/abc/{segment}           # 断言，为配合SetPath测试，{segment}的内容最后被SetPath取代
          filters:
            # 302表示返回到浏览器的状态码，以此来执行重定向
            # - RedirectTo=302, http://www.baidu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.atguigu.com/

            # 添加请求头参数
            # - PrefixPath=/pay # http://localhost:9527/pay/gateway/filter
            # - SetPath=/pay/gateway/{segment}  # {segment}表示占位符，你写abc也行但要上下一致

#            - AddRequestHeader=X-Request-atguigu1, value1
#            - AddRequestHeader=X-Request-atguigu2, value2
#            - RemoveRequestHeader=sec-ch-ua-platform # 移除请求头参数
#            - SetRequestHeader=sec-fetch-mode, Blue-updatebyzzyy # 修改请求头参数
#            - AddRequestParameter=customerId,9527001 # 增加请求参数
#            - RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除
        - id: pay_routh2 #pay_routh1
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/**
          filters:
            - My=statusKey




